name = str(input("Enter Your name : "))
age = str(input("Enter Your age : "))
location = str(input("Enter Your location : "))
country = str(input("Enter Your country : "))
religion  = str(input("Enter Your religion : "))
email = str(input("Enter Your email : "))
password = str(input("Enter Your password  : "))
print("Welcome",name ,"....","Your data is secure")
print("Log in successfully")